apiVersion: v1
kind: Service
metadata:
  name: nats-service
  labels:
    app: nats
spec:
  type: ClusterIP
  ports:
  - name: client
    port: 4222
    targetPort: client
  - name: cluster
    port: 6222
    targetPort: cluster
  - name: monitor
    port: 8222
    targetPort: monitor
  selector:
    app: nats
