apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

resources:
  - namespace.yaml
  - ../../base/nats
  - ../../base/tmanager
  - ../../base/pmanager
  - ../../base/testagent

labels:
  - includeSelectors: false
    includeTemplates: true
    pairs:
      environment: dev

#configMapGenerator:
#  - name: tmanager-config
#    behavior: merge

#  - name: pmanager-config
#    behavior: merge
