apiVersion: apps/v1
kind: Deployment
metadata:
  name: testagent
  labels:
    app: testagent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testagent
  template:
    metadata:
      labels:
        app: testagent
    spec:
      containers:
        - name: testagent
          image: testagent:latest
          imagePullPolicy: Never
          ports:
            - name: http
              containerPort: 8181
          env:
            - name: NATS_URL
              value: "nats://nats-service:4222"
            - name: TESTAGENT_URI
              value: "nats://nats-service:4222"
            - name: TESTAGENT_BUCKET
              value: "cfm-bucket"
            - name: TESTAGENT_STREAM
              value: "cfm-stream"
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 256Mi