apiVersion: apps/v1
kind: Deployment
metadata:
  name: pmanager
  labels:
    app: pmanager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pmanager
  template:
    metadata:
      labels:
        app: pmanager
    spec:
      containers:
        - name: pmanager
          image: pmanager:latest
          imagePullPolicy: Never
          ports:
            - name: http
              containerPort: 8181
          env:
            - name: NATS_URL
              value: "nats://nats-service:4222"
            - name: PM_URI
              value: "nats://nats-service:4222"
            - name: PM_BUCKET
              value: "cfm-bucket"
            - name: PM_STREAM
              value: "cfm-stream"
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 256Mi