apiVersion: v1
kind: Service
metadata:
  name: pmanager-service
  labels:
    app: pmanager
spec:
  type: NodePort
  ports:
    - name: http
      port: 8181
      targetPort: http
      nodePort: 30081
  selector:
    app: pmanager