apiVersion: apps/v1
kind: Deployment
metadata:
  name: tmanager
  labels:
    app: tmanager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tmanager
  template:
    metadata:
      labels:
        app: tmanager
    spec:
      containers:
        - name: tmanager
          image: tmanager:latest
          imagePullPolicy: Never
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: NATS_URL
              value: "nats://nats-service:4222"
            - name: TM_URI
              value: "nats://nats-service:4222"
            - name: TM_BUCKET
              value: "cfm-bucket"
            - name: TM_STREAM
              value: "cfm-stream"
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 256Mi
#          livenessProbe:
#            httpGet:
#              path: /health
#              port: http
#            initialDelaySeconds: 15
#            periodSeconds: 10
#          readinessProbe:
#            httpGet:
#              path: /ready
#              port: http
#            initialDelaySeconds: 5
#            periodSeconds: 5