apiVersion: v1
kind: Service
metadata:
  name: tmanager-service
  labels:
    app: tmanager
spec:
  type: NodePort
  ports:
    - name: http
      port: 8080
      targetPort: http
      nodePort: 30080
  selector:
    app: tmanager